### ISSUE TITLE
Result is good but could be smoother

### ISSUE THREAD

**Issue by kaisark** [zubairahmed-ai/Live-Background-Blur#1]
It seems like there is extra padding around the foreground object. Any ideas on how to reduce padding (smoothen) to get a more accurate profile/outline???

Code:
https://pastebin.com/UNeNFbgm

Related post:?
https://www.pyimagesearch.com/2018/11/26/instance-segmentation-with-opencv/

A simple yet effective update to our instance segmentation pipeline would be to potentially:

Use morphological operations to increase the size of our mask
Apply a small amount of Gaussian blurring to the mask itself, helping smooth the mask
Scale the mask values to the range [0, 1]
Create an alpha layer using the scaled mask
Overlay the smoothed mask + person ROI on the blurred background

Alternatively, you could compute the contours of the mask itself and then apply contour approximation to help create a “more smoothed” mask.

![animated gif-downsized_large](https://user-images.githubusercontent.com/3580312/51791018-f7411b80-216a-11e9-843a-fb0647fef63f.gif)

**Comment by zubairahmed-ai** [comment]
This is something that I wanted to apply on this myself but I have not got the chance to do that if you know this Adrian post is inspired by this post. But feel free to add these enhancements into the code and send me a PR
