### ISSUE TITLE
Model: from model import Deeplabv3

### ISSUE THREAD

**Issue by shliang0603** [zubairahmed-ai/Live-Background-Blur#2]
@zubairahmed-ai  Hi, I don't find the model  and can't find the module of Deeplabv3 ?

**Comment by zubairahmed-ai** [comment]
In the linked blog post I wrote I included link to the project that [I used to run DeepLabv3+](https://github.com/bonlime/keras-deeplab-v3-plus) you can see [in the code](https://github.com/bonlime/keras-deeplab-v3-plus/blob/master/extract_weights.py) that it downloads the weights at runtime
